import './app_flow.cy'
import './workout/all_types_3_exercises.cy'
import './workout/create_delete_saved_workout.cy'
import './workout/drop_set_1_exercise.cy'
import './workout/like_unlike_workout.cy'
import './workout/straight_set_1_exercise.cy'
import './workout/timed_set_1_exercise.cy'
