// Auth types
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const FETCH_USER_ACCOUNT_DATA = 'FETCH_USER_ACCOUNT_DATA'
export const ADD_NEW_USERNAME = 'ADD_NEW_USERNAME'
export const SET_USER_STATUS_SIGNED_IN = 'SET_USER_STATUS_SIGNED_IN'
export const SET_USER_STATUS_SIGNED_OUT = 'SET_USER_STATUS_SIGNED_OUT'
export const SET_USER_ACCOUNT_DATA = 'SET_USER_ACCOUNT_DATA'

// Workout Types
export const FETCH_WORKOUT_DATA = 'FETCH_WORKOUT_DATA'
export const SET_WORKOUT_DATA = 'SET_WORKOUT_DATA'
export const SET_WORKOUT_FINISHED = 'SET_WORKOUT_FINISHED'
export const SET_COMPLETED_WORKOUT_DATA = 'SET_COMPLETED_WORKOUT_DATA'

// Character Types
export const FETCH_CHARACTER_DATA = 'FETCH_CHARACTER_DATA'
export const INC_COINS = 'INC_COINS'
export const DEC_COINS = 'DEC_COINS'
export const INC_EXP = 'INC_EXP'
export const DEC_EXP = 'DEC_EXP'
export const INC_HEALTH = 'INC_HEALTH'
export const DEC_HEALTH = 'DEC_HEALTH'
