name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2\
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm start
        
